// This key needs to match the same key in protected/DO_NOT_UPLOAD/experienceTables.js otherwise it won't show up
let experience = {
    // "": {  
    //     "title": "",
    //     "company": "",
    //     "dates": "",
    //     "location": "",
    //     "summary": ""
    //     "responsbilities": [],
    //     "skills": [],
    //     "technology": []
    // },
    "Snapser - Technical Writer Contractor": {  
        "title": "Technical Writer (Contractor)",
        "company": "Snapser",
        "dates": "February 19, 2024 - March 15, 2024",
        "location": "Remote",
        "summary": "I collaborated with the CEO and stakeholders to revise primary content for a public product launch in two months. I revamped 17 documents with quick turnaround based on team feedback and implemented user-friendly navigation for a more intuitive documentation site structure, resulting in improved content organization and enhanced user experience. I also managed documentation projects from start to finish, identified and resolved HTML rendering issues, and optimized visual design elements for optimal performance",
        "responsbilities": ['Collaborated with the CEO and key stakeholders to revise primary content for a public product launch in two months.','Updated 17 documents based on team feedback with a same or next-day turnaround.','Proposed and implemented user-friendly navigation for the documentation site in collaboration with the CEO and platform advisor. This involved restructuring 74 documents, including renaming, relocating, merging redundant content, and removing outdated material.','Revised welcome, concept, and quick start guide documents, while also creating new landing and sub-landing pages to enhance user guidance.','Conducted a comprehensive assessment of the team\'s content, identifying areas for improvement and proposing a streamlined and user-centric documentation site structure. This initiative resulted in enhanced content organization, improved user navigation, and increased overall efficiency.','Enhanced user experience by adding descriptive links to all 8 newly created sub-landing pages and updating 15 markdown files to replace hardcoded URLs. This initiative improved website navigation, accessibility, and search engine optimization.','Created and integrated over 20 new supporting images for platform illustration.','Identified and archived outdated content, proactively removing obsolete features through regular team reviews.','Implemented cross-linking strategies to enhance content discoverability and findability.','Effectively managed documentation projects from inception to completion, ensuring timely delivery and accuracy. Responsible for overseeing budgetary aspects, tracking project milestones, and submitting monthly invoices.','Identified and reported HTML rendering issues, leading to improvements in functionality. Edited CSS and typescript files to enhance user experience and ensure optimal performance.','Collaborated with the team to troubleshoot and resolve visual design challenges, specifically focusing on optimizing button properties for enhanced user experience.'
        ],
        "skills": ['Technical writing','Technical communication','Markdown','CSS','Git','Project management','HTML','Information architecture', 'Asynchronous communication', 'Style guide', 'Content development', 'Content feedback integration', 'Content planning', 'Content research', 'Documentation analysis', 'Documentation site design', 'Project management scheduling', 'Project manager', 'Project planning management', 'Proofreading', 'Technical writing', 'Verbal communication', 'Written communication', 'Cross-functional team relationship development', 'Synchronous communication','Documentation communication'],
        "technology": ['Github', 'VS Code', 'Snagit', 'Google Docs', 'Google Drive', 'Zoom', 'Gmail', 'Google Sheets']
    },
    "Epic Games - Senior Technical Writer": {  
        "title": "Senior Technical Writer",
        "company": "Epic Games",
        "dates": "March 20, 2023 - October 2, 2023",
        "location": "Larkspur, California (Remote)",
        "summary": 'Experienced in collaborating, researching, and editing multiple Unreal Engine documents in markdown while ensuring compliance and improving search results. Successfully integrated stakeholder and peer feedback into 16 new or updated documents, contributed to release notes, and conducted peer reviews to maintain quality standards. I played a key role in identifying and resolving software bugs, redefining localization policies, enhancing team documentation processes, and mentoring junior technical writers.',
        "responsbilities": ['Collaborated, researched, and edited multiple Unreal Engine documents, communicated with stakeholders, audited documents for compliance, improved search results, and contributed to various documentation tasks, including peer reviews and bug reporting, while also assisting in redefining localization team policies.', 'Collaborated, researched, wrote, and integrated SME and peer feedback into 16 new or updated Unreal Engine (UE) docs that were well received by the UE Dev community.','Communicated with key stakeholders, shared links to the published content, and noted any feedback on the docs I completed and published.','Audited 25 UE docs and took notes to suggest improvements that would ensure adherence to the Doc team\'s publication policies.','Identified and fixed poor metadata, resulting in improved search results in 80 docs.','Wrote or revised release notes for 7 different Unreal Engine product areas while collaborating with SMEs.','Identified and fixed broken links or images in 10 docs.','Researched and organized notes for revising 5 ongoing docs.','Conducted 6 peer reviews of fellow tech writers\' docs to ensure they followed the Doc team\'s style guide and were free of errors before publication.','Identified and resolved 182 Jira tickets, as they were either unnecessary, redundant, or represented completed tasks that were never closed.','Wrote a few Jira queries to assist the Doc team in identifying unassigned and unresolved tickets.','Gathered documentation requirements from the teams supported by reviewing various planning docs, backlogged Jira tickets, and by directly speaking with 5 different Product Owners and POCs.','Revised the New Hire Onboarding Checklist document to include missing notes, important apps, and links to critical docs to ensure future new hires have the most complete guide possible.','Participated in testing and provided feedback for new internal documentation tools.','Wrote team documentation to raise awareness of new policies and features for publishing content.','Gave two presentations on the topics of Docathons and Work Journaling, and answered questions on how to integrate those strategies on the individual level to several teammates.','Reported software bugs to the support team while writing Unreal Engine documentation.','Helped redefine the localization team\'s policy around code comments.'],
        "skills": ['Content analysis', 'Content curation', 'Content development', 'Content feedback integration', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation communication', 'Documentation maintenance', 'Documentation procedures', 'project reports', 'Project management scheduling', 'Project manager', 'Project planning management', 'Proofreading', 'Style guide', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', '3D animation', '3D modeling', 'Asynchronous communication', 'Collaboration', 'Computer animation', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Mentor', 'Presenter', 'Synchronous communication','Technical communication','Desktop recording', 'Video editing', 'Video production'],
        "technology": ['CSS', 'HTML', 'JavaScript', 'Markdown', 'Node.js', 'Perforce', 'Windows', 'Photoshop', 'Unreal Engine', 'Maya', 'Google Calendar', 'Google Docs', 'Google Drive', 'Gmail', 'Google Slides', 'VS Code', 'Confluence', 'Jira', 'Snagit', 'Workday', 'ADP', 'Google Sheets']
    },
    "Documentation Engineer Meta": {
        "title": "Documentation Engineer",
        "company": "Meta",
        "dates": "December 9 2019 - November 9 2022",
        "location": "Menlo Park, CA",
        "summary": "Authored/Co-authored 360 pages, made 1,792 edits, verified 59 pages, and archived 66 pages for backend automation and capacity management services. I empowered engineers by structuring teams effectively, setting up collaboration systems, and leading the Docathon Program for 2.5 years. I collaborated with seven teams on various documentation types, authored monthly status reports, and championed better engineering projects. I mentored eight junior Documentation Engineers, conducted doc consults, and managed 29 successful docathon events.",
        "responsbilities": {
            "General": ['Authored / co-authored 360 pages, made 1,792 edits, verified 59, archived 66 pages, and provided feedback on 39 pages.', 'Empowered engineers by providing structure for teams to contribute effectively while taking on more core and strategic documentation responsibilities by setting up an effective system for engineers to collaborate and crowdsource content.', 'Authored / collaborated on documentation with seven teams including back-end service automation and capacity management that included doc types such as landing pages, program overviews, glossaries, conceptual guides, tutorials, and similar user / internal-centric informational content.', 'Wrote and published a monthly documentation status report that brought awareness of documentation efforts, celebrated documentation contributors, and showcased meaningful content metrics.', 'Created, planned, and executed vision plans / roadmaps to align documentation effects across multiple cross-functional teams.', 'Led efforts to revamp, design, or create wiki sites by collaborating with several key stakeholders by applying a standard and uniform appearance, navigation, and content structure based on regular feedback and industry standards.', 'Received and utilized expert training on how to conduct formal interviews for technical writing positions and applied those skills to reviewing nearly 100 candidate resumes and cover letters and interviewed 23 candidates.', 'Owned and led the Docathon Program for 2.5 years, organized and conducted dozens of docathon events with the opportunity for teams to focus on documentation efforts for a select period of time.', 'Collaborated with several fellow Documentation Engineers to create new dashboards, templates, and documentation for self-service and writer-led docathon efforts.', 'Gave five presentations to cross-functional teams across multiple organizations on topics including how to plan for docathons, keeping a work journal, and how to write onboarding guides', 'Mentored / trained 8 fellow Documentation Engineers to help them with their onboarding responsibilities, provided feedback, answered questions about work culture or tool usage, and provided moral support and encouragement.'],
            "Better Engineering": ['Championed better engineering projects.', 'Piloted and shared the Documentarians of the Month process that celebrated the documentation efforts of team members, promoted documentation efforts, and brought general awareness of documentation improvements monthly.', 'Created and shared several SQL queries for the general purpose of collecting various points of metrics related to documentation improvement and docathon tracking.', 'Crafted onboarding guides and mentored three fellow Documentation Engineers to boost their productivity and decrease the time it took for new Documentation Engineers to become effective in their roles.', 'Conducted twelve doc consults to help teams assess their documentation needs, provided guidance on areas they could improve upon, and guided them to hold a docathon with their consent.', 'Developed a model for task-based project management for documentation that was appreciated and adopted by other Documentation Engineers.', 'Created / hosted 3-4 Infra Doc Eng social events every month for one year to boost team morale and help teammates connect.', 'Created and shared several dashboards to track wiki metrics to better inform monthly and bi-annual reports.', 'Created a series of automation features within Meta that provided forms and triaged questions to appropriate wikispaces or Q&A forums that greatly reduced on-call burden.'],
            "Docathon Program": ['Supported the Docathon Program and trained fellow Documentation Engineers on how to conduct a docathon.', 'Took over the Docathon Program in March 2020, improved the program, recorded metrics, expanded guidance / training, and produced internal and external team reports on the status and impact of the program.', 'Wrote and published bi-annual reports on the effects and impact of the Docathon Program.', 'Managed, coordinated, and organized 29 single or multiple teams docathon events to ensure the success and impact of maintaining documentation with the teams / wikis involved.', 'Captured and reported docathon metrics from hundreds of Wikispaces from 173 docathon events.', 'Created and awarded three different badges for those who had an outstanding performance during a docathon event to recognize their excellence and commitment to better documentation.', 'Wrote or updated guidance on how to host a tech writer-led or self-led docathon.', 'Created guidance on how to conduct a multi-team or org-wide docathon by expanding the guidance of single-team docathons.']
        },
        "skills": ['Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation at scale', 'Documentation communication', 'Documentation maintenance', 'Documentation procedures', 'Documentation reporting', 'Documentation site design', 'Documentation tracking', 'information architecture', 'program/project reports', 'Project management scheduling', 'Project manager', 'Project planning management', 'Proofreading', 'Site documentation', 'Style guides', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', 'Analytics', 'Analytics dashboard designer', 'Asynchronous communication', 'Collaboration', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Interviewer', 'Mentor', 'Presenter', 'Program leader', 'Social event organizer', 'Synchronous communication'],
        "technology": ['Markdown', 'MySQL', 'Proprietary analytics', 'Mercurial', 'Proprietary issue tracker', 'Mac OS', 'Unix', 'Photoshop', 'Illustrator', 'Google Docs', 'Google Forms', 'Google Sheets', 'Google Slides', 'VS Code', 'MediaWiki', 'Outlook', 'ADP', 'Workday']
    },
    "Principal Tech Writer I Axway Appcelerator": {
        "title": "Principal Tech Writer I",
        "company": "Axway/Appcelerator",
        "dates": "February 2016 - October 31, 2019",
        "location": "Santa Clara, CA (remote)",
        "summary": "I managed the collaboration and publication of documentation, interfacing with developers and managers to address documentation needs across Axway and Appcelerator products. I streamlined the documentation publication process, reducing it from over 4 hours to about 38 minutes, and created tools/scripts for content migration into Confluence, handling thousands of documents. I improved the documentation site's UX, navigation, and search features, trained technical writers on API documentation processes, and administered the Confluence server. I also led special projects, including creating tools for document conditioning, building Solr indexes, implementing CSP rules for security, and collaborating with platform teams for issue resolution and migration tasks.",
        "responsbilities": {
            "General": ['Managed the collaboration and publication of Appcelerator\'s documentation.', 'Interfaced with numerous developers and managers to gather information about various updates and addressed documentation needs of all Axway and Appcelerator products and features.', 'Improved and maintained documentation publication scripts process from over 4 hours down to about 38 minutes.', 'Created several tools and scripts to migrate content from various sources into Atlassian\'s Confluence to handle six thousand plus documents, images, and PDF files.', 'Maintained documentation site by improving UX, site navigation, and search features.', 'Trained fellow technical writers and engineers on how to understand, write, modify, and publish API documentation and all processes involved therein.'],
            "Wrote numerous Node.js and Bash-based tools for tasks such as": ['Mass HTML links verification', 'Interface for Confluence REST API (for migration, ingression, and re-ordering of content)', 'Testing Solr indexes', 'Hundreds of HTML document extraction, modification, and upload to Atlassian Confluence server', 'Report generation for API and npm dependencies changes for release notes'],
            "Administered Appcelerator's Confluence server by": ['Adding, removing, and/or banning users', 'Updating plugins', 'Writing user macros', 'Space creation, setup, permissioning, and archival processes', 'Space migration from on instance to another'],
            "Gave several presentations to the tech writer teams on topics of": ['JIRA Dashboard basics', 'Introduction to Confluence', 'Confluence content extraction and publication', 'Documentation publication automation', 'Tools for link checking'],
            "Special projects": ['Created Confluence ingestion and conditioning tools to handle 1100+ documents', 'Built a new Solr index for indexing Appcelerator guides and API documents', 'Created a series of CSP rules that should prevent any XSS issues on the Appc docs site', 'Met with Zoomin platform management and developers to discuss and resolve numerous Zoomin platform issues', 'Worked with a representative from the Syncplicity team to plan, implement, troubleshoot, migrate, and verify Syncplicity\'s 600+ document set to Axway\'s internal wiki utilizing tools I wrote']
        },
        "skills": ['Archives wiki', 'API documentation', 'Automation in application development', 'Confluence API', 'Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation automation', 'Documentation communication', 'Documentation maintenance', 'Documentation procedures', 'Documentation publication automation', 'Documentation reporting', 'Documentation site design', 'Documentation tracking', 'Information architecture', 'IT documentation', 'Project reporting', 'Project management scheduling', 'Proofreading', 'Remote training', 'REST API', 'ReSTful', 'SDK', 'Site documentation', 'Style guide', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', 'Analytics', 'Asynchronous communication', 'Collaboration', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Mentor', 'Presenter', 'Synchronous communication'],
        "technology": ['Bash', 'CSS', 'HTML', 'JavaScript', 'JSON', 'Markdown', 'Yaml', 'Node.js', 'Google Analytics', 'Apache Solr', 'Git', 'Github', 'Mac OS', 'Photoshop', 'FileZilla', 'Google Calendar', 'Google Docs', 'Google Drawings', 'Google Drive', 'Gmail', 'Google Sheets', 'Google Slides', 'Appcelerator Studio', 'Atom', 'Eclipse', 'VS Code', 'Confluence', 'Jira', 'Record My Desktop', 'ADP', 'Unix', 'XML']
    },
    "Senior Technical Writer Appcelerator": {
        "title": "Senior Technical Writer",
        "company": "Appcelerator",
        "dates": "November 2015 - February 2016",
        "location": "San Jose, CA",
        "summary": "I was responsible for researching and writing various types of technical documentation, including release notes, product guides, API updates for the Appcelerator platform, and other general documentation requirements. I also played a key role in revising the documentation structure and publication process to ensure clarity and accessibility for users. I developed documentation tools and scripts to streamline the publication process, improving efficiency and accuracy in delivering high-quality documentation to users and stakeholders. My contributions helped enhance the overall user experience and support system for the organization's products and services.",
        "responsbilities": ['Researched and wrote release notes, product guides, API updates, and all other general documentation requirements.', 'Revised documentation structure and publication process.', 'Wrote documentation tools and scripts to streamline the documentation publication process.'],
        "skills": ['API documentation','Archives wiki', 'Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation communication', 'Documentation maintenance', 'Documentation procedures', 'Documentation publication automation', 'Documentation reporting', 'Documentation site design', 'Documentation tracking', 'Information architecture', 'Program/project reporting', 'Project management scheduling', 'Proofreading', 'REST API', 'ReSTful', 'SDK', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', 'Analytics', 'Asynchronous communication', 'Collaboration', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Presenter', 'Synchronous communication'],
        "technology": ['Bash', 'JavaScript', 'Markdown', 'Yaml', 'Node.js', 'Git', 'Github', 'Mac OS', 'Unix', 'Photoshop', 'FileZilla', 'Google Calendar', 'Google Docs', 'Google Drawings', 'Google Drive', 'Gmail', 'Google Sheets', 'Google Slides', 'Appcelerator Studio', 'Atom', 'Eclipse', 'VS Code', 'Confluence', 'Jira', 'Record My Desktop', 'ADP', 'XML']
    },
    "Technical Writer API Documentation Contractor Walmart eCommerce": {
        "title": "Technical Writer - API Documentation (Contractor)",
        "company": "Walmart eCommerce",
        "dates": "October 2015 - November 2015",
        "location": "Sunnyvale, CA",
        "summary": "I played a pivotal role in researching, revising, writing, and amending documentation related to the Marketplace API and customer onboarding processes. I collaborated closely with developers and subject matter experts to gather in-depth information about various aspects of Walmart's eCommerce portal.",
        "responsbilities": ['Researched, revised, wrote, and amended Marketplace API and customer onboarding documentation.', 'Interfaced with developers and subject matter experts to gather information about various aspects of Walmart\'s eCommerce portal.', 'Revised, edited, and published documentation relating to Walmart\'s eCommerce portal.'],
        "skills": ['Content development', 'API documentation','Content feedback integration', 'Content planning', 'Content research', 'Documentation', 'Documentation reporting', 'Proofreading', 'Style guide', 'Technical writing', 'Verbal communication', 'Writing', 'Written communication', 'Asynchronous communication', 'Collaboration', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Synchronous communication'],
        "technology": ['Mac OS', 'Photoshop', 'Confluence', 'Jira', 'Outlook', 'Excel', 'Word', 'Sharepoint']
    },
    "Tech Writer Coupa": {
        "title": "Tech Writer",
        "company": "Coupa",
        "dates": "March 2015 - September 2015",
        "location": "San Mateo, CA",
        "summary": "I collaborated with developers and integration specialists to update API and integration documentation, focusing on readability and searchability. I reviewed internal training materials, authored instructional documents for documentation processes, and managed a Jira project for streamlined task tracking.",
        "responsbilities": ['Interfaced with developers and integration specialists to update and write new documents for API and integration documentation, restructuring the integration documentation for maximum readability and searchability.', 'Reviewed and revised internal training documentation.', 'Authored several in-house instructional documents on how to search, organize, collect, and write API and integration documentation.', 'Set up, organized, and managed a Jira project used for documentation tasks and general tracking.'],
        "skills": ['API documentaiton', 'Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation maintenance', 'Documentation procedures', 'Documentation reporting', 'Jira administration', 'Proofreading', 'REST API', 'SDK', 'Style guide', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', 'Asynchronous communication', 'Collaboration', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Interviewer', 'Synchronous communication', 'Desktop recording', 'Digital Photography'],
        "technology": ['Confluence', 'Jira', 'Markdown', 'Madcap Flare', 'Yaml', 'Mac OS', 'Photoshop', 'Premiere', 'Record My Desktop', 'Visio']
    },           
    "Documentation Specialist PDI DreamWorks Animation": {
        "title": "Documentation Specialist",
        "company": "PDI/DreamWorks Animation",
        "dates": "July 2009 - March 2015",
        "location": "Redwood City, CA",
        "summary": "I authored comprehensive software documentation covering diverse topics such as animation, character rigging, modeling, and pipeline tools. I collaborated with production artists to create documentation and pioneered training video production processes. I standardized document types into a wiki format for cross-departmental use and revamped the studio's training curriculum. I designed a unified navigation scheme in Atlassian's Confluence and managed an analytics system for data-driven decisions. I deployed documentation sites, developed user macros and custom features for Confluence, and mentored interns for two years. I contributed to social event planning and initiated 'Doc Days' for collaborative documentation efforts. I also conducted user polls, established documentation standards, and performed periodic reviews for optimization.",
        "responsbilities": ['Authored proprietary software documentation covering a wide range of topics, including animation, character rigging, lighting, modeling, pipeline tools, third-party platforms, plugins, and more.', 'Collaborated with production artists to create documentation, including writing and generating images.', 'Pioneered the development of training video production processes and tools for creating internal training materials that supported both educational and production requirements.', 'Standardized various document types into a wiki format for use across multiple departments.', 'Collaborated in revamping the studio\'s training curriculum content and delivery system.', 'Collaboratively designed a unified navigation scheme for both production and non-production departments, implemented through Atlassian\'s Confluence.', 'Researched, implemented, managed, and maintained an analytics system integrated into Confluence, providing essential data used to inform the documentation team.', 'Authored and deployed documentation sites for production teams through collaboration with department heads and leaders.', 'Collaborated in the development and maintenance of user macros and custom features for Confluence services, utilizing HTML, CSS, JavaScript, Java, and managing other wiki administration tasks.', 'Active member of the social events planning committee, helped setup and tear down for events, photographed most events, and led several events myself.', 'Managed tasks and mentored interns for two years.', 'Contributed to the creation, launch, and promotion of \'Doc Days\' (an early version of Docathons).', 'Conducted user polls to gather feedback and collect wish-list items for the documentation or updating of technical features.', 'Established documentation standards and structures using templates and performed periodic reviews of usage and implementation.', 'Actively participated in the social events planning committee, assisting in event setup and teardown, photographing most events, and even taking the lead in organizing several events.'],
        "skills": ['Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation at scale', 'Documentation maintenance', 'Documentation procedures', 'Documentation reporting', 'Documentation site design', 'Documentation tracking', 'Information architecture', 'IT documentation', 'Live classroom training', 'Project reporting', 'Project management scheduling', 'Project manager', 'Project planning management', 'Proofreading', 'Remote training', 'Site documentation', 'Style guide', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', '3D animation', '3D modeling', 'Analytics', 'Analytics dashboard designer', 'Asynchronous communication', 'Collaboration', 'Computer animation', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Educator', 'Interviewer', 'Mentor', 'Presenter', 'Program leader', 'Social event organizer', 'Software training', 'Synchronous communication', 'Teaching', 'Trainer', 'Confluence administration'],
        "technology": ['Bash', 'CSS3', 'HTML5', 'Java', 'JavaScript', 'Markup', 'Python', 'XHTML', 'Windows', 'Linux', 'Unix', 'CVS', 'After Effects', 'Illustrator', 'Lightroom', 'Photoshop', 'Premiere', 'Autodesk Maya', 'Outlook', 'Confluence', 'Jira', 'Piwik', 'Proprietary animation programs', 'Proprietary animation tools']
    },
    "Training Specialist PDI DreamWorks Animation": {
        "title": "Training Specialist",
        "company": "PDI/DreamWorks Animation",
        "dates": "January 5, 2005 - July 2009",
        "location": "Redwood City, CA",
        "summary": "I provided education for new hires and conducted cross-training sessions on proprietary and third-party technologies for existing employees. I authored documentation and created videos to support educational and production needs, implementing standardization of document types into a wiki format. Collaborating with production artists, I created documentation and supported the FX Challenge program for training college graduates. I contributed to data migration and tool development, transitioning from static HTML to a wiki format and then to Atlassian Confluence. I participated in overhauling the studio's training curriculum, supported social event planning, administered user polls for feedback, and established documentation standards using templates with regular reviews for optimization.",
        "responsbilities": ['Provided education for new hires and conducted cross-training sessions for existing employees in proprietary and third-party technologies.','Authored documentation and created videos to support both educational and production requirements.','Implemented standardization of various document types into a wiki format across multiple departments.', 'Collaborated with production artists in the creation of documentation, including writing and generating images.','Assisted in supporting documentation efforts for the FX Challenge program, which aimed to train college graduates in the FX pipeline.','Contributed to the migration of data and the development of tools, transitioning from static HTML pages to a wiki (Oddmuse), and ultimately to Atlassian Confluence.', 'Participated in the overhaul of the studio\'s training curriculum content and delivery system.', 'Actively participated in the social events planning committee, assisting in event setup and teardown, photographing most events, and even taking the lead in organizing several events.', 'Administered user polls to collect feedback and compile wish-list items for documenting or updating technical features.', 'Established documentation standards and structures using templates and conducted regular reviews of usage and implementation.'],
        "skills": ['Content analysis', 'Content Curation', 'Content development', 'Content feedback integration', 'Content management systems', 'Content planning', 'Content research', 'Documentation', 'Documentation analysis', 'Documentation at scale', 'Documentation maintenance', 'Documentation procedures', 'Documentation reporting', 'Documentation site design', 'Documentation tracking', 'Information architecture', 'IT documentation', 'Live classroom training', 'Project reporting', 'Project management scheduling', 'Project planning management', 'Proofreading', 'Site documentation', 'Style guide', 'Technical writing', 'Verbal communication', 'Wiki documentation', 'Writing', 'Written communication', '3D animation', '3D modeling', 'Analytics', 'Asynchronous communication', 'Collaboration', 'Computer animation', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Educator', 'Mentor', 'Presenter', 'Social event organizer', 'Software training', 'Synchronous communication', 'Teaching', 'Trainer','Digital Photography', 'Video production', 'Video recording'],
        "technology": ['Markup', 'Python', 'XHTML', 'Windows', 'Linux', 'Unix', 'CVS', 'After Effects', 'FrameMaker', 'Illustrator', 'Lightroom', 'Photoshop', 'Premiere', 'Autodesk Maya', 'Outlook', 'Confluence', 'Jira', 'Proprietary animation programs', 'Proprietary animation tools', 'Camtasia']
    },
    "Faculty Art Institute of Washington": {
        "title": "Faculty",
        "company": "Art Institute of Washington",
        "dates": "September 2002 - January 2005",
        "location": "Arlington, VA",
        "summary": "I served as an instructor teaching 3D animation, modeling, special effects, and sound design. During this time, I played a key role in developing and revising the animation and 3D curricula to ensure comprehensive and up-to-date education for students.",
        "responsbilities": ['Taught 3D animation, modeling, special effects, and sound design.', 'Developed and revised the animation and 3D curricula.'],
        "skills": ['Content analysis', 'Content Curation', 'curriculum development', 'Live classroom training', 'Project planning management', 'Proofreading', 'Technical writing', 'Verbal communication', 'Writing', 'Written communication', 'Desktop recording', 'Digital Photography', 'Video production', 'Video recording', '3D animation', '3D modeling', 'Asynchronous communication', 'Collaboration', 'Computer animation', 'Cross-functional team communication', 'Cross-functional team relationship development', 'Educator', 'Mentor', 'Presenter', 'Software training', 'Synchronous communication', 'Teaching'],
        "technology": ['After Effects', 'Illustrator', 'Photoshop', 'Premiere', 'Autodesk Maya', 'Excel', 'Outlook', 'Word']
    },
    "Adjunct Professor George Washington University": {
        "title": "Adjunct Professor",
        "company": "George Washington University",
        "dates": "August 2004 - December 2004",
        "location": "Washington, DC",
        "summary": "I instructed Computer Science (CS) students in 3D fundamentals using Autodesk's Maya application.",
        "responsbilities": ['Instructed 3D fundamentals to CS students via Autodesk\'s Maya application, provided project feedback, and created additional educational materials.'],
        "skills": ['Content analysis', 'Live classroom training', 'Project planning management', 'Proofreading', 'Technical writing', 'Verbal communication', 'Writing', 'Written communication', '3D animation', '3D modeling', 'Asynchronous communication', 'Collaboration', 'Computer animation', 'Cross-functional team communication', 'Educator', 'Mentor', 'Software training', 'Synchronous communication', 'Teaching'],
        "technology": ['Photoshop', 'Autodesk Maya', 'Excel', 'Outlook', 'Word']
    }
}
