// ** this is missing a ton of monsters that are listed in monsters.js

// Note: when you add a new monster to monsters.js, make sure to add which environment is can be found in.

const environments = {
  "Arctic": [
    "Adult White Dragon",
    "Ancient White Dragon",
    "Frost Giant",
    "Ice Devil",
    "Ice Mephit",
    "Polar Bear",
    "Remorhaz",
    "White Dragon Wyrmling",
    "Winter Wolf",
    "Yeti",
    "Young White Dragon"
  ],
  "Coastal": [
    "Aboleth",
    "Adult Brass Dragon",
    "Adult Bronze Dragon",
    "Ancient Brass Dragon",
    "Ancient Bronze Dragon",
    "Dragon Turtle",
    "Giant Crab",
    "Giant Sea Horse",
    "Giant Shark",
    "Kraken",
    "Killer Whale",
    "Merfolk",
    "Merrow",
    "Plesiosaurus",
    "Reef Shark",
    "Sahuagin",
    "Sea Hag",
    "Sea Horse"
  ],
  "Desert": [
    "Adult Brass Dragon",
    "Ancient Brass Dragon",
    "Camel",
    "Dust Mephit",
    "Galeb Duhr",
    "Giant Scorpion",
    "Lamia",
    "Scorpion"
  ],
  "Forest": [
    "Adult Green Dragon",
    "Ancient Green Dragon",
    "Awakened Shrub",
    "Awakened Tree",
    "Black Bear",
    "Blink Dog",
    "Brown Bear",
    "Dryad",
    "Ettercap",
    "Giant Bat",
    "Giant Boar",
    "Giant Elk",
    "Giant Frog",
    "Giant Owl",
    "Giant Poisonous Snake",
    "Giant Spider",
    "Giant Toad",
    "Giant Wolf Spider",
    "Green Dragon Wyrmling",
    "Green Hag",
    "Griffon",
    "Harpy",
    "Hippogriff",
    "Lizard",
    "Owl",
    "Panther",
    "Phase Spider",
    "Poisonous Snake",
    "Pseudodragon",
    "Satyr",
    "Spider",
    "Sprite",
    "Tiger",
    "Treant",
    "Twig Blight",
    "Werebear",
    "Werewolf",
    "Wolf",
    "Young Green Dragon"
  ],
  "Grassland": [
    "Allosaurus",
    "Ape",
    "Baboon",
    "Centaur",
    "Elk",
    "Giant Ape",
    "Giant Elk",
    "Giant Hyena",
    "Giant Lizard",
    "Giant Vulture",
    "Gorgon",
    "Griffon",
    "Hawk",
    "Hyena",
    "Lion",
    "Mastiff",
    "Mule",
    "Owl",
    "Panther",
    "Pony",
    "Pteranodon",
    "Rhinoceros",
    "Riding Horse",
    "Saber-Toothed Tiger",
    "Vulture",
    "Warhorse",
    "Wolf",
    "Worg"
  ],
  "Hill": [
    "Axe Beak",
    "Giant Goat",
    "Goat",
    "Hill Giant",
    "Ogre",
    "Ogre Zombie"
  ],
  "Jungle": [
    "Ape",
    "Giant Ape",
    "Giant Constrictor Snake",
    "Giant Lizard",
    "Giant Tiger",
    "Giant Wasp",
    "Lizardfolk",
    "Pteranodon",
    "Tiger"
  ],
  "Mountain": [
    "Adult Silver Dragon",
    "Ancient Silver Dragon",
    "Azer",
    "Cloud Giant",
    "Giant Goat",
    "Goat",
    "Griffon",
    "Young Silver Dragon"
  ],
  "Swamp": [
    "Adult Black Dragon",
    "Ancient Black Dragon",
    "Black Dragon Wyrmling",
    "Black Pudding",
    "Bullywug",
    "Chuul",
    "Crocodile",
    "Giant Constrictor Snake",
    "Giant Frog",
    "Giant Toad",
    "Green Hag",
    "Hydra",
    "Lizardfolk",
    "Ochre Jelly",
    "Shambling Mound",
    "Will-o'-Wisp",
    "Young Black Dragon"
  ],
  "Underdark": [
    "Aboleth",
    "Beholder",
    "Cloaker",
    "Darkmantle",
    "Deep Gnome (Svirfneblin)",
    "Drow",
    "Duergar",
    "Flameskull",
    "Gelatinous Cube",
    "Gibbering Mouther",
    "Grick",
    "Grimlock",
    "Hook Horror",
    "Illithid",
    "Mimic",
    "Myconid",
    "Nothic",
    "Otyugh",
    "Purple Worm",
    "Roper",
    "Rust Monster",
    "Shrieker",
    "Spectator",
    "Troglodyte",
    "Umber Hulk",
    "Violet Fungus",
    "Xorn"
  ],
  "Underwater": [
    "Aboleth",
    "Chuul",
    "Crab",
    "Dragon Turtle",
    "Giant Crab",
    "Giant Octopus",
    "Giant Sea Horse",
    "Giant Shark",
    "Hunter Shark",
    "Kraken",
    "Killer Whale",
    "Merfolk",
    "Merrow",
    "Octopus",
    "Plesiosaurus",
    "Quipper",
    "Reef Shark",
    "Sahuagin",
    "Sea Hag",
    "Sea Horse",
    "Water Elemental"
  ],
  "Urban": [
    "Acolyte",
    "Adult Gold Dragon",
    "Ancient Gold Dragon",
    "Archmage",
    "Assassin",
    "Bandit",
    "Bandit Captain",
    "Commoner",
    "Cult Fanatic",
    "Cultist",
    "Doppelganger",
    "Draft Horse",
    "Gladiator",
    "Guard",
    "Half-Red Dragon Veteran",
    "Knight",
    "Mage",
    "Mastiff",
    "Medusa",
    "Noble",
    "Priest",
    "Rakshasa",
    "Rat",
    "Scout",
    "Spy",
    "Thug",
    "Veteran",
    "WereRat"
  ],
  "Celestial Plane": [
    "Deva",
    "Planetar",
    "Solar",
    "Unicorn"
  ],
  "Abyssal Plane": [
    "Balor",
    "Dretch",
    "Glabrezu",
    "Hezrou",
    "Marilith",
    "Nalfeshnee",
    "Quasit",
    "Succubus/Incubus",
    "Vrock"
  ],
  "Infernal Plane": [
    "Barbed Devil",
    "Bearded Devil",
    "Bone Devil",
    "Chain Devil",
    "Erinyes",
    "Horned Devil",
    "Ice Devil",
    "Imp",
    "Lemure",
    "Pit Fiend"
  ],
  "Elemental Air": [
    "Air Elemental",
    "Djinni",
    "Invisible Stalker",
    "Steam Mephit"
  ],
  "Elemental Earth": [
    "Earth Elemental",
    "Galeb Duhr",
    "Xorn"
  ],
  "Elemental Fire": [
    "Efreeti",
    "Fire Elemental",
    "Magma Mephit",
    "Magmin",
    "Salamander"
  ],
  "Elemental Water": [
    "Water Elemental"
  ]
}
